[package]
name = "zahra-snake-launcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
rodio = "0.17.1"
tempfile = { version = "3.8.0", features = ["nightly"] }
